FROM ruby:2.3.0

# Install dependencies
RUN apt-get update -qq
RUN apt-get install -y build-essential libpq-dev nodejs

RUN mkdir /gitHubModuleExtractor
WORKDIR /gitHubModuleExtractor
ADD Gemfile /gitHubModuleExtractor/Gemfile
ADD Gemfile.lock /gitHubModuleExtractor/Gemfile.lock
RUN bundle install
ADD . /gitHubModuleExtractor